[package]
name = "datamodel-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.15.0"
psl.workspace = true
regex.workspace = true
itertools.workspace = true
base64 = "0.13.1"

[dev-dependencies]
expect-test = "1.4.0"
indoc.workspace = true
itertools.workspace = true
