[package]
name = "migration-engine-cli"
version = "0.1.0"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
migration-connector = { path = "../connectors/migration-connector" }
migration-core = { path = "../core" }
user-facing-errors = { path = "../../libs/user-facing-errors" }

anyhow = "1.0.26"
futures = "0.3"
json-rpc-stdio = { path = "../../libs/json-rpc-stdio" }
serde_json = "1.0"
structopt = "0.3.8"
thiserror = "1.0.9"
tokio = { version = "=0.2.13", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-error = "0.1.2"

[dev-dependencies]
tempfile = "3.1.0"
test-setup = { path = "../../libs/test-setup" }
url = "2.1.1"
quaint = { git = "https://github.com/prisma/quaint" }

[features]
default = ["sql"]
sql = ["migration-core/sql"]

[[bin]]
name = "migration-engine"
path = "src/main.rs"
