[toolchain]
channel = "1.91.1"
components = ["clippy", "rustfmt", "rust-src"]
targets = [
    # Wasm target for serverless and edge environments.
    "wasm32-unknown-unknown",

    # Server targets we support.
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "aarch64-apple-darwin",
]
