[package]
edition = "2021"
name = "prisma-models"
version = "0.0.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
psl = { path = "../../psl/psl" }
itertools = "0.10"
once_cell = "1.3"
prisma-value = { path = "../../libs/prisma-value" }
bigdecimal = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["float_roundtrip"] }
thiserror = "1.0"
