[package]
edition = "2021"
name = "prisma-models"
version = "0.0.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
psl.workspace = true
dml = { path = "../../libs/dml", features = ["default_generators"] }
itertools = "0.10"
once_cell = "1.3"
prisma-value = { path = "../../libs/prisma-value" }
bigdecimal = "0.3"
serde.workspace = true
serde_json = { version = "1.0", features = ["float_roundtrip"] }
thiserror = "1.0"
