[package]
edition = "2021"
name = "prisma-models"
version = "0.0.0"

[dependencies]
psl.workspace = true
itertools = "0.10"
prisma-value = { path = "../../libs/prisma-value" }
bigdecimal = "0.3"
thiserror = "1.0"
getrandom = { version = "0.2" }
uuid = { workspace = true, optional = true }
cuid = { git = "https://github.com/prisma/cuid-rust", branch = "jkomyno/wasm32", optional = true }
cuid2 = { git = "https://github.com/prisma/cuid-rust", branch = "jkomyno/wasm32", optional = true }
nanoid = { version = "0.4.0", optional = true }
chrono = { version = "0.4.6", features = ["serde"] }

[target.'cfg(target_arch = "wasm32")'.dependencies.getrandom]
version = "0.2"
features = ["js"]

[features]
# Support for generating default UUID, CUID, nanoid and datetime values.
default_generators = ["uuid/v4", "cuid", "cuid2", "nanoid"]
