[package]
name = "black-box-tests"
version = "0.1.0"
edition.workspace = true

[dependencies]
query-engine-tests = { path = "../connector-test-kit-rs/query-engine-tests" }
query-tests-setup = { path = "../connector-test-kit-rs/query-tests-setup" }
reqwest.workspace = true
anyhow.workspace = true
serde_json.workspace = true
indoc.workspace = true
tokio.workspace = true
user-facing-errors.workspace = true
insta.workspace = true
enumflags2.workspace = true
regex.workspace = true
