[package]
name = "black-box-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
query-engine-tests = { path = "../connector-test-kit-rs/query-engine-tests" }
query-tests-setup = { path = "../connector-test-kit-rs/query-tests-setup" }
reqwest = "0.11"
anyhow = "1.0"
serde_json = "1.0"
indoc.workspace = true
tokio.workspace = true
user-facing-errors.workspace = true
insta = "1.7.1"
enumflags2 = "0.7"
query-engine-metrics = {path = "../metrics"}
regex = "1.9.3"
