[package]
name = "parser-database"
version = "0.1.0"
edition.workspace = true

[dependencies]
diagnostics.workspace = true
schema-ast.workspace = true
indexmap.workspace = true
enumflags2.workspace = true
itertools.workspace = true
either.workspace = true
hashbrown.workspace = true
