[package]
edition = "2021"
name = "sql-schema-connector"
version = "0.1.0"

[features]
vendored-openssl = ["quaint/vendored-openssl"]

[dependencies]
psl.workspace = true
quaint = { workspace = true, features = [
    "all-native",
    "expose-drivers",
    "pooled",
    "fmt-sql",
] }
tokio.workspace = true
serde.workspace = true
indoc.workspace = true
uuid.workspace = true
indexmap.workspace = true

prisma-value = { path = "../../../libs/prisma-value" }
schema-connector = { path = "../schema-connector" }
sql-schema-describer = { path = "../../sql-schema-describer", features = [
    "all-native",
] }
datamodel-renderer = { path = "../../datamodel-renderer" }
sql-ddl = { path = "../../../libs/sql-ddl" }
user-facing-errors = { path = "../../../libs/user-facing-errors", features = [
    "sql",
    "all-native",
] }

chrono.workspace = true
connection-string.workspace = true
enumflags2.workspace = true
once_cell = "1.3"
regex.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
url.workspace = true
either = "1.6"
sqlformat = "0.2.1"
sqlparser = "0.32.0"
versions = "6.1.0"
sqlx-sqlite = { version = "0.8.0" }
sqlx-core = "0.8.0"
[dev-dependencies]
expect-test = "1"
