[package]
name = "builtin-psl-connectors"
version = "0.1.0"
edition = "2021"

[dependencies]
datamodel = { path = "../../libs/datamodel/core" }
native-types = { path = "../../libs/native-types" }

connection-string = "0.1"
serde_json = { version = "1.0", features = ["float_roundtrip"] }
once_cell = "1.3"
regex = "1"
enumflags2 = "0.7"
either = "1.6.1"
lsp-types = "0.91.1"
