[package]
name = "builtin-psl-connectors"
version = "0.1.0"
edition = "2021"

[dependencies]
psl-core = { path = "../psl-core" }

connection-string = "0.1"
either = "1.6.1"
enumflags2 = "0.7"
indoc = "1"
lsp-types = "0.91.1"
once_cell = "1.3"
regex = "1"
