[package]
name = "migration-connector"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>"]
edition = "2018"

[dependencies]
datamodel = { path = "../../../libs/datamodel/core" }
user-facing-errors = { path = "../../../libs/user-facing-errors" }

anyhow = "1.0.26"
async-trait = "0.1.17"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
tracing-error = "0.1.2"
sha2 = "0.9.1"
tracing = "0.1.19"
