[package]
name = "migration-connector"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>"]
edition = "2018"

[dependencies]
datamodel = { path = "../../../libs/datamodel" }
prisma-query = { git = "https://github.com/prisma/prisma-query", branch = "async-await" }
chrono = { version = "0.4" }

serde = "1.0"
serde_json = "1.0"

failure = "0.1"
