[package]
name = "migration-connector"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>"]
edition = "2018"

[dependencies]
datamodel = { path = "../../../libs/datamodel/core" }
chrono = { version = "0.4" }

serde = "1.0"
serde_json = "1.0"

failure = "0.1"
user-facing-errors = { path = "../../../libs/user-facing-errors" }
