[package]
name = "migration-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
psl = { path = "../../../psl/psl" }
user-facing-errors = { path = "../../../libs/user-facing-errors" }

chrono = "0.4"
enumflags2 = "0.7"
sha2 = "0.9.1"
tracing = "0.1"
tracing-error = "0.2"
