[package]
name = "dmmf"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.3.0"
psl.workspace = true
serde.workspace = true
serde_json.workspace = true
schema = { path = "../schema" }
schema-builder = { path = "../schema-builder" }
indexmap = { version = "1.7", features = ["serde-1"] }
prisma-models = { path = "../prisma-models" }

wasm-bindgen = { version = "0.2.84" }
tsify = { version = "0.4.3", features = ["json"] }

[dev-dependencies]
expect-test = "1.2.2"
indoc = "1.0.3"
pretty_assertions = "1"
flate2 = "1.0"
similar = { version = "2.2.1", features=["text", "inline", "bytes"] }
colored = "2.0.0"
