[package]
name = "dmmf"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.3.0"
itertools.workspace = true
psl.workspace = true
serde.workspace = true
serde_json.workspace = true
schema = { path = "../schema" }
indexmap.workspace = true
query-structure = { path = "../query-structure", features = [
    "default_generators",
] }

[dev-dependencies]
expect-test = "1.2.2"
indoc.workspace = true
pretty_assertions = "1"
flate2 = "1.0"
similar = { version = "2.2.1", features = ["text", "inline", "bytes"] }
colored = "2.0.0"
itertools.workspace = true
