[package]
name = "mongodb-introspection-connector"
version = "0.1.0"

[dependencies]
mongodb = "2.3.0"
thiserror = "1.0"
async-trait = "0.1"
mongodb-client = { path = "../../../libs/mongodb-client" }
psl.workspace = true
introspection-connector = { path = "../introspection-connector" }
user-facing-errors = { path = "../../../libs/user-facing-errors" }
native-types = { path = "../../../libs/native-types" }
mongodb-schema-describer = { path = "../../../libs/mongodb-schema-describer" }
enumflags2 = "0.7"
indoc = "1"
futures = "0.3"
serde_json = "1"
regex = "1"
once_cell = "1"
convert_case = "0.5"

[dev-dependencies]
tokio.workspace = true
names = { version = "0.12", default-features = false }
expect-test = "1"
url = "2"
