[package]
name = "json-rpc-api"
version = "0.1.0"
edition = "2024"
description = "JSON-RPC API definitions for the Prisma Schema Engine"

[dependencies]
serde.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
tsify.workspace = true
