[package]
name = "json-rpc-api"
version = "0.1.0"
edition = "2024"
description = "JSON-RPC API definitions for the Prisma Schema Engine"

[dependencies]
heck.workspace = true
serde.workspace = true
toml.workspace = true
