[package]
name = "prisma-fmt"
version = "0.1.0"
authors = ["Emanuel Joebstl <emanuel.joebstl@gmail.com>"]
edition = "2018"

[dependencies]
datamodel = { path = "../libs/datamodel/core" }
structopt = "0.3"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
