[package]
name = "prisma-fmt"
version = "0.1.0"
authors = ["Emanuel Joebstl <emanuel.joebstl@gmail.com>"]
edition = "2021"

[dependencies]
datamodel = { path = "../libs/datamodel/core" }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
serde = { version = "1.0.90", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
structopt = "0.3"

[dev-dependencies]
expect-test = "1"
indoc = "1"

[features]
# sigh please don't ask :(
vendored-openssl = []
