[package]
name = "prisma-fmt"
version = "0.1.0"
authors = ["Emanuel Joebstl <emanuel.joebstl@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
datamodel = { path = "../libs/datamodel/core" }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
serde = { version = "1.0.90", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
structopt = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.77"

[features]
# sigh please don't ask :(
vendored-openssl = []
