[package]
name = "psl"
version = "0.1.0"
edition = "2021"

[dependencies]
builtin-psl-connectors = { path = "../builtin-connectors" }
psl-core = { path = "../psl-core" }

[dev-dependencies]
dissimilar = "1.0.4"
dml = { path = "../../libs/dml" }
expect-test = "1.1.0"
indoc = "1"
