[package]
name = "psl"
version = "0.1.0"
edition = "2021"

[dependencies]
psl-core = { path = "../../libs/datamodel/core", package = "datamodel", default-features = false }

[dev-dependencies]
dissimilar = "1.0.4"
expect-test = "1.1.0"
indoc = "1"
native-types = { path = "../../libs/native-types" }

[features]
default_generators = ["psl-core/default_generators"]
