[package]
name = "schema-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
psl.workspace = true
quaint.workspace = true
serde.workspace = true
serde_json.workspace = true
user-facing-errors = { path = "../../../libs/user-facing-errors" }

chrono = "0.4"
enumflags2.workspace = true
sha2 = "0.9.1"
tracing = "0.1"
tracing-error = "0.2"
