[package]
name = "schema"
version = "0.1.0"
edition.workspace = true

[dependencies]
query-structure.workspace = true
psl.workspace = true

[dev-dependencies]
codspeed-criterion-compat.workspace = true

[[bench]]
name = "schema_builder_bench"
harness = false

[features]
all_connectors = ["psl/all"]
