[package]
name = "qe-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
psl.workspace = true
mongodb-client = { path = "../../libs/mongodb-client" }
migration-core = { path = "../core" }
test-setup = { path = "../../libs/test-setup" }

connection-string = "*"
enumflags2 = "*"
mongodb = "2.3.0"
tempfile = "3.3.0"
url = "2"
quaint.workspace = true
