[package]
name = "qe-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
psl = { path = "../../psl/psl" }
mongodb-client = { path = "../../libs/mongodb-client" }
migration-core = { path = "../core" }
test-setup = { path = "../../libs/test-setup" }

connection-string = "*"
enumflags2 = "*"
mongodb = "2.1.0"
tempfile = "3.3.0"
url = "2"

[dependencies.quaint]
git = "https://github.com/prisma/quaint"
features = [
    "sqlite",
    "postgresql",
    "mysql",
    "mssql",
]
