[package]
name = "migration-engine-tests"
version = "0.1.0"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sql"]
sql = ["barrel", "sql-schema-describer", "sql-migration-connector", "quaint", "user-facing-errors/quaint"]

[dependencies]
datamodel = { path = "../../libs/datamodel/core" }
migration-connector = { path = "../connectors/migration-connector" }
migration-core = { path = "../core" }
sql-migration-connector = { path = "../connectors/sql-migration-connector", optional = true }
sql-schema-describer = { path = "../../libs/sql-schema-describer", optional = true }
user-facing-errors = { path = "../../libs/user-facing-errors" }

test-macros = { path = "../../libs/test-macros" }
test-setup = { path = "../../libs/test-setup" }

anyhow = "1.0"
barrel = { version = "0.6.5", features = ["sqlite3", "mysql", "pg"], optional = true }
once_cell = "1.2.0"
pretty_assertions = "0.6"
quaint = { version = "0.1", optional = true }
serde_json = "1.0.45"
tempfile = "3.1.0"
tokio = { version = "0.2", features = ["macros"] }
url = "2.1.1"
git2 = { version = "0.11.0", default-features = false }
tracing = "0.1.12"
tracing-futures = "0.2.1"
futures = "0.3.1"
