[package]
name = "migration-engine-tests"
version = "0.1.0"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sql"]
sql = ["barrel", "sql-schema-describer", "sql-migration-connector", "quaint", "user-facing-errors/quaint"]

[dependencies]
datamodel = { path = "../../libs/datamodel/core" }
migration-connector = { path = "../connectors/migration-connector" }
migration-core = { path = "../core" }
sql-migration-connector = { path = "../connectors/sql-migration-connector", optional = true }
sql-schema-describer = { path = "../../libs/sql-schema-describer", optional = true }
user-facing-errors = { path = "../../libs/user-facing-errors" }
test-macros = { path = "../../libs/test-macros" }
test-setup = { path = "../../libs/test-setup" }
prisma-value = { path = "../../libs/prisma-value" }
enumflags2 = "0.6.0"

anyhow = "1.0"
barrel = { git = "https://github.com/prisma/barrel.git", features = ["sqlite3", "mysql", "pg", "mssql"], optional = true, branch = "mssql-support" }
chrono = "0.4.15"
indoc = "1.0.2"
pretty_assertions = "0.6"
serde = "1"
serde_json = "1.0.45"
tempfile = "3.1.0"
tokio = { version = "0.2.13", features = ["macros"] }
tracing = "0.1.12"
tracing-futures = "0.2.1"
url = "2.1.1"

[dependencies.quaint]
git = "https://github.com/prisma/quaint"
optional = true
features = ["serde-support", "tracing-log"]
