[package]
name = "migration-engine-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
psl.workspace = true
migration-core = { path = "../core" }
sql-migration-connector = { path = "../connectors/sql-migration-connector" }
sql-schema-describer = { path = "../../libs/sql-schema-describer" }
user-facing-errors = { path = "../../libs/user-facing-errors" }
test-macros = { path = "../../libs/test-macros" }
test-setup = { path = "../../libs/test-setup" }
prisma-value = { path = "../../libs/prisma-value" }

bigdecimal = "0.3"
chrono = "0.4.15"
colored = "2"
connection-string = "0.1.13"
enumflags2 = "0.7"
expect-test = "1.1.0"
indoc = "1.0.3"
jsonrpc-core = "17.0.0"
once_cell = "1.8.0"
pretty_assertions = "1"
serde.workspace = true
serde_json.workspace = true
tempfile = "3.1.0"
tokio.workspace = true
tracing = "0.1"
tracing-futures = "0.2"
url = "2.1.1"
quaint.workspace = true
