[package]
name = "sql-introspection-tests"
version = "0.1.0"
edition.workspace = true

[dependencies]
schema-connector = { workspace = true, features = [
    "all-native",
] }
sql-schema-connector = { workspace = true, features = [
    "all-native",
] }
sql-schema-describer = { workspace = true, features = [
    "all-native",
] }
psl = { workspace = true, features = ["all"] }
test-macros.workspace = true
user-facing-errors = { workspace = true, features = [
    "all-native",
] }
test-setup.workspace = true
itertools.workspace = true

enumflags2.workspace = true
connection-string.workspace = true
pretty_assertions.workspace = true
tracing-futures.workspace = true
tokio.workspace = true
tracing.workspace = true
indoc.workspace = true
expect-test.workspace = true
url.workspace = true
quaint = { workspace = true, features = ["all-native"] }

[dependencies.barrel]
workspace = true
features = ["sqlite3", "mysql", "pg", "mssql"]
