[package]
name = "sql-introspection-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
schema-connector = { path = "../connectors/schema-connector" }
sql-schema-connector = { path = "../connectors/sql-schema-connector" }
sql-schema-describer = { path = "../sql-schema-describer" }
psl = { workspace = true, features = ["all"] }
test-macros = { path = "../../libs/test-macros" }
user-facing-errors = { path = "../../libs/user-facing-errors", features = [
    "all-native",
] }
test-setup = { path = "../../libs/test-setup" }

enumflags2.workspace = true
connection-string.workspace = true
pretty_assertions = "1"
tracing-futures = "0.2"
tokio.workspace = true
tracing.workspace = true
indoc.workspace = true
expect-test = "1.1.0"
url.workspace = true
quaint = { workspace = true, features = ["all-native"] }

[dependencies.barrel]
git = "https://github.com/prisma/barrel.git"
features = ["sqlite3", "mysql", "pg", "mssql"]
branch = "mssql-support"
