[package]
name = "introspection-connector"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datamodel = { path = "../../../libs/datamodel" }
failure = "0.1"

serde = { version = "1.0", features = ["derive"]}