[package]
name = "introspection-connector"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>"]
edition = "2021"

[dependencies]
async-trait = "0.1.17"
datamodel = { path = "../../../libs/datamodel/core" }
thiserror = "1.0.9"
anyhow = "1.0.26"
enumflags2 = "0.7"

serde = { version = "1.0", features = ["derive"]}
serde_json = { version = "1.0", features = ["float_roundtrip"] }
user-facing-errors = { path = "../../../libs/user-facing-errors" }
