[package]
edition = "2021"
name = "query-engine-tests"
version = "0.1.0"

[dependencies]
enumflags2.workspace = true
anyhow = "1.0"
serde_json.workspace = true
query-test-macros = { path = "../query-test-macros" }
query-tests-setup = { path = "../query-tests-setup" }
indoc.workspace = true
tracing.workspace = true
tracing-futures = "0.2"
colored = "2"
chrono.workspace = true
psl.workspace = true
base64 = "0.13"
uuid.workspace = true
tokio.workspace = true
user-facing-errors.workspace = true
prisma-value = { path = "../../../libs/prisma-value" }
query-engine-metrics = { path = "../../metrics"}
once_cell = "1.15.0"
futures.workspace = true
paste = "1.0.14"

[dev-dependencies]
insta = { version = "1.7.1", features = ["json", "redactions"] }
itertools.workspace = true
