[package]
edition.workspace = true
name = "query-engine-tests"
version = "0.1.0"

[dependencies]
enumflags2.workspace = true
anyhow.workspace = true
serde_json.workspace = true
query-test-macros = { path = "../query-test-macros" }
query-tests-setup = { path = "../query-tests-setup" }
indoc.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
colored.workspace = true
chrono.workspace = true
psl.workspace = true
base64.workspace = true
uuid.workspace = true
cuid.workspace = true
ulid.workspace = true
tokio.workspace = true
user-facing-errors.workspace = true
prisma-value.workspace = true
prisma-metrics.workspace = true
futures.workspace = true
paste.workspace = true

[dev-dependencies]
insta = { workspace = true, features = ["json", "redactions"] }
itertools.workspace = true
