[package]
edition = "2021"
name = "mongodb-schema-connector"
version = "0.1.0"

[dependencies]
psl = { workspace = true, features = ["mongodb"] }
mongodb-client = { path = "../../../libs/mongodb-client" }
mongodb-schema-describer = { path = "../../mongodb-schema-describer" }
datamodel-renderer = { path = "../../datamodel-renderer" }
schema-connector = { path = "../schema-connector" }
user-facing-errors = { path = "../../../libs/user-facing-errors", features = [
    "all-native",
] }

enumflags2.workspace = true
futures = "0.3"
mongodb = "2.8.0"
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
convert_case = "0.6.0"
once_cell = "1.8.0"
regex = "1.7.3"
indoc.workspace = true

[dev-dependencies]
serde.workspace = true
dissimilar = "1.0.3"
once_cell = "1.8.0"
url.workspace = true
expect-test = "1"
names = { version = "0.12", default-features = false }
