[package]
name = "sql-introspection-connector"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
introspection-connector = { path = "../introspection-connector" }
sql-schema-describer = { path = "../../../libs/sql-schema-describer" }
prisma-inflector = { path = "../../../libs/prisma-inflector" }
datamodel = { path = "../../../libs/datamodel/core" }
quaint = { git = "https://github.com/prisma/quaint.git" }
sql-connection = { path  = "../../../libs/sql-connection" }
failure = "0.1"
log = "0.4"
regex = "1.2"
url = "1.7"

[dev-dependencies]
fern = "0.5"
pretty_assertions = "0.6"
barrel = { version = "0.6.3-alpha.0", features = ["sqlite3", "mysql", "pg"] }
postgres = { version = "0.16.0-rc.1", features = ["with-serde_json-1", "with-chrono-0_4", "with-uuid-0_7"] }
mysql = { version = "*" }
r2d2 = "0.8"

