[package]
authors = ["Marcus BÃ¶hm <boehm@prisma.io>"]
edition = "2021"
name = "sql-introspection-connector"
version = "0.1.0"

[features]
vendored-openssl = ["quaint/vendored-openssl"]

[dependencies]
anyhow = "1.0.26"
async-trait = "0.1.17"
psl.workspace = true
introspection-connector = { path = "../introspection-connector" }
datamodel-renderer = { path = "../../datamodel-renderer" }
once_cell = "1.3"
regex = "1.2"
bigdecimal = "0.3"
serde.workspace = true
serde_json.workspace = true
sql-schema-describer = { path = "../../../libs/sql-schema-describer" }
thiserror = "1.0.9"
tracing = "0.1"
tracing-futures = "0.2"
user-facing-errors = { workspace = true, features = ["sql"] }
enumflags2 = "0.7.1"
quaint.workspace = true

[dev-dependencies]
pretty_assertions = "1"
expect-test = "1.1.0"

