[package]
name = "driver-adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
once_cell = "1.15"
serde.workspace = true
serde_json.workspace = true
psl.workspace = true
tracing = "0.1"
tracing-core = "0.1"
metrics = "0.18"
uuid = { version = "1", features = ["v4"] }

# Note: these deps are temporarily specified here to avoid importing them from tiberius (the SQL server driver).
# They will be imported from quaint-core instead in a future PR.
num-bigint = "0.4.3"
bigdecimal = "0.3.0"
chrono = "0.4.20"
futures = "0.3"

[dev-dependencies]
expect-test = "1"
tokio.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
napi.workspace = true
napi-derive.workspace = true
quaint.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys.workspace = true
quaint = { path = "../../quaint" }
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
tsify.workspace = true
