[package]
name = "driver-adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
once_cell = "1.15"
serde.workspace = true
serde_json.workspace = true
tracing = "0.1"
tracing-core = "0.1"
metrics = "0.18"
uuid = { version = "1", features = ["v4"] }
pin-project = "1"
wasm-rs-dbg = "0.1.2"
serde_repr.workspace = true

futures = "0.3"

[dev-dependencies]
expect-test = "1"
tokio = { version = "1.0", features = ["macros", "time", "sync"] }
wasm-rs-dbg.workspace = true
wasm-bindgen-test.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
napi.workspace = true
napi-derive.workspace = true
quaint.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
quaint = { path = "../../quaint" }
js-sys.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
tsify.workspace = true
