[package]
name = "datamodel-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psl = { path = "../../psl/psl" }

[dev-dependencies]
expect-test = "1.4.0"