[package]
edition = "2021"
name = "sql-schema-describer"
version = "0.1.0"

[features]
sqlite-native = ["quaint/pooled", "quaint/sqlite-native", "quaint/expose-drivers"]
all-native = [
    "sqlite-native",
]

[dependencies]
prisma-value = { path = "../../libs/prisma-value" }
psl = { workspace = true, features = ["all"] }

either = "1.8.0"
async-trait.workspace = true
bigdecimal = "0.3"
enumflags2.workspace = true
indexmap.workspace = true
indoc.workspace = true
once_cell = "1.3"
regex.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-error = "0.2"
tracing-futures.workspace = true
quaint = { workspace = true, features = [
    "fmt-sql",
] }

[dev-dependencies]
expect-test = "1.2.2"
pretty_assertions = "1"
test-macros = { path = "../../libs/test-macros" }
test-setup = { path = "../../libs/test-setup" }
tokio.workspace = true
