[package]
name = "query-tests-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json.workspace = true
query-structure = { path = "../../query-structure" }
once_cell = "1"
qe-setup = { path = "../qe-setup" }
request-handlers = { path = "../../request-handlers" }
tokio.workspace = true
query-core = { path = "../../core", features = ["metrics"] }
sql-query-connector = { path = "../../connectors/sql-query-connector" }
query-engine = { path = "../../query-engine" }
psl.workspace = true
user-facing-errors = { path = "../../../libs/user-facing-errors" }
telemetry = { path = "../../../libs/telemetry" }
thiserror = "1.0"
async-trait.workspace = true
nom = "7.1"
itertools.workspace = true
regex.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-error = "0.2"
colored = "2"
indoc.workspace = true
enumflags2.workspace = true
hyper = { version = "0.14", features = ["full"] }
indexmap.workspace = true
prisma-metrics.path = "../../../libs/metrics"
quaint.workspace = true
jsonrpc-core = "17"
insta.workspace = true
panic-utils.path = "../../../libs/panic-utils"

# Only this version is vetted, upgrade only after going through the code,
# as this is a small crate with little user base.
parse-hyperlinks = "0.23.3"
strip-ansi-escapes = "0.1.1"
log = "0.4.22"
env_logger = "0.11.6"
