[package]
name = "query-tests-setup"
version = "0.1.0"
authors = ["Dominic Petrick <dompetrick@gmail.com>"]
edition = "2021"

[dependencies]
serde_json = "1.0"
datamodel-connector = { path = "../../../libs/datamodel/connectors/datamodel-connector" }
mongodb-datamodel-connector = { path = "../../../libs/datamodel/connectors/mongodb-datamodel-connector" }
sql-datamodel-connector = { path = "../../../libs/datamodel/connectors/sql-datamodel-connector" }
prisma-models = { path = "../../prisma-models" }
lazy_static = "1.4"
enum_dispatch = "0.3"
qe-setup = { path = "../../../migration-engine/qe-setup" }
request-handlers = { path = "../../request-handlers" }
tokio = "1.0"
query-core = { path = "../../core" }
query-engine = { path = "../../query-engine"}
datamodel = { path = "../../../libs/datamodel/core" }
user-facing-errors = { path = "../../../libs/user-facing-errors" }
thiserror = "1.0"
async-trait = "0.1"
nom = "7.1"
itertools = "0.10"
regex = "1"
serde = "1.0"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-error = "0.2"
colored = "2"
indoc = "1.0"
enumflags2 = "0.7"
hyper = { version = "0.14", features = ["full"] }
indexmap = { version = "1.0", features = ["serde-1"] }

# Only this version is vetted, upgrade only after going through the code,
# as this is a small crate with little user base.
parse-hyperlinks = "0.23.4"
