[package]
name = "query-tests-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json.workspace = true
prisma-models = { path = "../../prisma-models" }
once_cell = "1"
qe-setup = { path = "../qe-setup" }
request-handlers = { path = "../../request-handlers" }
tokio.workspace = true
query-core = { path = "../../core", features = ["metrics"] }
sql-query-connector = { path = "../../connectors/sql-query-connector" }
query-engine = { path = "../../query-engine"}
psl.workspace = true
user-facing-errors = { path = "../../../libs/user-facing-errors" }
thiserror = "1.0"
async-trait = "0.1"
nom = "7.1"
itertools = "0.10"
regex = "1"
serde.workspace = true
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-error = "0.2"
colored = "2"
indoc.workspace = true
enumflags2 = "0.7"
hyper = { version = "0.14", features = ["full"] }
indexmap = { version = "1.0", features = ["serde-1"] }
query-engine-metrics = {path = "../../metrics"}
quaint.workspace = true
jsonrpc-core = "17"

# Only this version is vetted, upgrade only after going through the code,
# as this is a small crate with little user base.
parse-hyperlinks = "0.23.3"
strip-ansi-escapes = "0.1.1"
