[package]
name = "query-tests-setup"
version = "0.1.0"
authors = ["Dominic Petrick <dompetrick@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
datamodel-connector = { path = "../../../libs/datamodel/connectors/datamodel-connector" }
mongodb-datamodel-connector = { path = "../../../libs/datamodel/connectors/mongodb-datamodel-connector" }
sql-datamodel-connector = { path = "../../../libs/datamodel/connectors/sql-datamodel-connector" }
prisma-models = { path = "../../../libs/prisma-models" }
lazy_static = "1.4"
enum_dispatch = "0.3"
migration-core = { path = "../../../migration-engine/core" }
request-handlers = { path = "../../request-handlers" }
tokio = "1.0"
query-core = { path = "../../core" }
datamodel = { path = "../../../libs/datamodel/core" }
thiserror = "1.0"
async-trait = "0.1"
nom = "6"
itertools = "0.10"
regex = "1"
serde = "1.0"
tracing = "0.1.12"
tracing-futures = "0.2.1"
tracing-subscriber = { version = "0.2", features = ["fmt"] }
tracing-error = "0.1.2"
colored = "2"
indoc = "1.0"
enumflags2 = "0.7"

# Only this version is vetted, upgrade only after going through the code,
# as this is a small crate with little user base.
parse-hyperlinks = "0.19.6"
