[package]
name = "query-tests-setup"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde_json.workspace = true
query-structure.workspace = true
qe-setup = { path = "../qe-setup" }
request-handlers.workspace = true
tokio.workspace = true
query-core.workspace = true
sql-query-connector.workspace = true
query-engine.workspace = true
psl.workspace = true
user-facing-errors.workspace = true
telemetry.workspace = true
thiserror.workspace = true
async-trait.workspace = true
nom.workspace = true
itertools.workspace = true
regex.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber.workspace = true
tracing-error.workspace = true
colored.workspace = true
indoc.workspace = true
enumflags2.workspace = true
hyper = { workspace = true, features = ["full"] }
indexmap.workspace = true
quaint.workspace = true
jsonrpc-core.workspace = true
insta.workspace = true
futures.workspace = true
panic-utils.workspace = true
parse-hyperlinks.workspace = true
strip-ansi-escapes.workspace = true
log.workspace = true
env_logger.workspace = true
