[package]
name = "schema-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
psl.workspace = true
schema = { path = "../schema" }
prisma-models = { path = "../prisma-models" }
once_cell = "1.3"

[dev-dependencies]
codspeed-criterion-compat = "1.1.0"

[dev-dependencies.criterion]
version = "0.4.0"
default-features = false
features = ["cargo_bench_support"]

[[bench]]
name = "schema_builder_bench"
harness = false
