[package]
name = "qe-setup"
version = "0.1.0"
edition.workspace = true

[dependencies]
psl.workspace = true
quaint.workspace = true
mongodb-client.workspace = true
schema-core.workspace = true
schema-connector.workspace = true
sql-schema-connector = { workspace = true, features = [
    "all-native",
] }
test-setup.workspace = true
enumflags2.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

connection-string.workspace = true
mongodb.workspace = true
url.workspace = true
