[package]
edition = "2021"
name = "sql-schema-describer"
version = "0.1.0"

[dependencies]
prisma-value = { path = "../../libs/prisma-value" }
psl.workspace = true

async-trait = "0.1.17"
bigdecimal = "0.3"
enumflags2 = { version = "0.7", features = ["serde"] }
indexmap = { version = "1.9.1", default_features = false }
indoc.workspace = true
once_cell = "1.3"
regex = "1.2"
serde.workspace = true
tracing = "0.1"
tracing-error = "0.2"
tracing-futures = "0.2"
quaint.workspace = true
either = "1.8.0"

[dev-dependencies]
expect-test = "1.2.2"
pretty_assertions = "1"
test-macros = { path = "../../libs/test-macros" }
test-setup = { path = "../../libs/test-setup" }
tokio.workspace = true
