[package]
name = "request-handlers"
version = "0.1.0"
edition = "2021"

[dependencies]
psl.workspace = true
query-structure = { path = "../query-structure" }
query-core = { path = "../core" }
user-facing-errors = { path = "../../libs/user-facing-errors" }
quaint.workspace = true
dmmf_crate = { path = "../dmmf", package = "dmmf" }
itertools.workspace = true
graphql-parser = { git = "https://github.com/prisma/graphql-parser", optional = true }
serde.workspace = true
serde_json.workspace = true
futures = "0.3"
indexmap.workspace = true
bigdecimal = "0.3"
thiserror = "1"
tracing.workspace = true
url.workspace = true
connection-string.workspace = true
once_cell = "1.15"

mongodb-query-connector = { path = "../connectors/mongodb-query-connector", optional = true }
sql-query-connector = { path = "../connectors/sql-query-connector", optional = true, default-features = false }

[dev-dependencies]
insta = "1.7.1"
schema = { path = "../schema" }
codspeed-criterion-compat = "1.1.0"

[features]
mongodb = ["mongodb-query-connector", "psl/mongodb"]
sql = ["sql-query-connector"]
postgresql = ["sql", "sql-query-connector/postgresql", "psl/postgresql"]
mysql = ["sql", "sql-query-connector/mysql", "psl/mysql"]
sqlite = ["sql", "sql-query-connector/sqlite", "psl/sqlite"]
driver-adapters = ["sql-query-connector/driver-adapters"]
native = [
    "mongodb",
    "sql",
    "graphql-protocol",
    "sql-query-connector/native_all",
    "query-core/metrics",
]
graphql-protocol = ["query-core/graphql-protocol", "dep:graphql-parser"]

[[bench]]
name = "query_planning_bench"
harness = false
