[package]
name = "request-handlers"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-models = { path = "../prisma-models" }
query-core = { path = "../core", features = ["metrics"] }
user-facing-errors = { path = "../../libs/user-facing-errors" }
quaint = { path = "../../quaint" }
psl.workspace = true
dmmf_crate = { path = "../dmmf", package = "dmmf" }
itertools = "0.10"
graphql-parser = { git = "https://github.com/prisma/graphql-parser" }
serde.workspace = true
serde_json.workspace = true
futures = "0.3"
indexmap = { version = "1.7", features = ["serde-1"] }
bigdecimal = "0.3"
thiserror = "1"
tracing = "0.1"
url = "2"
connection-string.workspace = true 
once_cell = "1.15"

mongodb-query-connector = { path = "../connectors/mongodb-query-connector", optional = true }
sql-query-connector = { path = "../connectors/sql-query-connector", optional = true }

[dev-dependencies]
insta = "1.7.1"
schema = { path = "../schema" }
codspeed-criterion-compat = "1.1.0"

[features]
default = ["sql", "mongodb", "native"]
mongodb = ["mongodb-query-connector"]
sql = ["sql-query-connector"]
driver-adapters = ["sql-query-connector/driver-adapters"]
native = ["mongodb", "sql-query-connector", "quaint/native", "query-core/metrics"]

[[bench]]
name = "query_planning_bench"
harness = false
