[package]
name = "request-handlers"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-models = { path = "../prisma-models" }
query-core = { path = "../core" }
user-facing-errors = { path = "../../libs/user-facing-errors" }
psl.workspace = true
dmmf_crate = { path = "../dmmf", package = "dmmf" }
itertools = "0.10"
graphql-parser = { git = "https://github.com/prisma/graphql-parser" }
serde.workspace = true
serde_json.workspace = true
futures = "0.3"
indexmap = { version = "1.7", features = ["serde-1"] }
bigdecimal = "0.3"
thiserror = "1"
tracing = "0.1"
url = "2"
connection-string = "0.1"

[dev-dependencies]
insta = "1.7.1"
schema-builder = { path = "../schema-builder" }