[package]
authors = ["Marcus BoÌˆhm <boehm@prisma.io>", "Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"
name = "migration-core"
version = "0.1.0"

[dependencies]
datamodel = { path = "../../libs/datamodel/core" }
migration-connector = { path = "../connectors/migration-connector" }
mongodb-migration-connector = { path = "../connectors/mongodb-migration-connector", optional = true }
sql-migration-connector = { path = "../connectors/sql-migration-connector", optional = true }
user-facing-errors = { path = "../../libs/user-facing-errors" }

async-trait = "0.1.17"
chrono = { version = "0.4", features = ["serde"] }
enumflags2 = "0.7.1"
jsonrpc-core = "17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
tracing = "0.1.10"
tracing-futures = "0.2.0"
url = "2.1.1"

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = ["macros"] }

[features]
default = ["sql", "mongodb"]
mongodb = ["mongodb-migration-connector"]
sql = ["sql-migration-connector"]
