[package]
name = "migration-core"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>", "Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

[dependencies]
migration-connector = { path = "../connectors/migration-connector" }
datamodel = { path = "../../libs/datamodel/core" }
sql-migration-connector = { path = "../connectors/sql-migration-connector", optional = true }
user-facing-errors = { path = "../../libs/user-facing-errors" }

anyhow = "1.0.26"
async-trait = "0.1.17"
chrono = { version = "0.4", features = ["serde"] }
futures = { version = "0.3", features = ["compat"] }
jsonrpc-core = "14.0"
quaint = { git = "https://github.com/prisma/quaint", optional = true }
serde = { version = "1.0" }
serde_json = "1.0"
thiserror = "1.0.9"
tracing = "0.1.10"
tracing-futures = "0.2.0"
tracing-error = "0.1.2"
url = "2"

[features]
default = ["sql"]
sql = ["quaint", "sql-migration-connector"]
