[package]
edition = "2021"
name = "migration-core"
version = "0.1.0"

[dependencies]
psl = { path = "../../psl/psl" }
migration-connector = { path = "../connectors/migration-connector" }
mongodb-migration-connector = { path = "../connectors/mongodb-migration-connector" }
sql-migration-connector = { path = "../connectors/sql-migration-connector" }
user-facing-errors = { path = "../../libs/user-facing-errors" }

async-trait = "0.1.17"
chrono = { version = "0.4", features = ["serde"] }
enumflags2 = "0.7.1"
jsonrpc-core = "17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
tokio = { version = "1.0", default_features = false }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-futures = "0.2"
url = "2.1.1"

[build-dependencies]
json-rpc-api-build = { path = "../json-rpc-api-build" }
