[package]
name = "migration-core"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>", "Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

[dependencies]
migration-connector = { path = "../connectors/migration-connector" }
datamodel = { path = "../../libs/datamodel" }
prisma-models = { path = "../../prisma-models" }
sql-migration-connector = { path = "../connectors/sql-migration-connector" }
sql-connection = { path = "../../libs/sql-connection" }
user-facing-errors = { path = "../../libs/user-facing-errors" }
clap = "2.33"
itertools = "0.8"

chrono = { version = "0.4", features = ["serde"] }
boolinator = "2.4.0"
url = "1.7"
log = "0.4"
env_logger = "0.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

failure = "0.1"

jsonrpc-core = "13.0"
jsonrpc-stdio-server = "13.0"

futures = "0.1"
tokio = "0.1"
tokio-threadpool = "0.1"

[dev-dependencies]
quaint = { git = "https://github.com/prisma/quaint.git" }
barrel = { version = "0.6.3-alpha.0", features = ["sqlite3", "mysql", "pg"] }
pretty_assertions = "0.6"
sql-schema-describer = { path = "../../libs/sql-schema-describer" }
migration-engine-macros = { path = "../macros" }
user-facing-errors = { path = "../../libs/user-facing-errors" }

[[bin]]
name = "migration-engine"
path = "src/main.rs"
