[package]
edition = "2021"
name = "query-connector"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
itertools.workspace = true
query-structure = {path = "../../query-structure"}
prisma-value = {path = "../../../libs/prisma-value"}
serde.workspace = true
serde_json.workspace = true
thiserror = "1.0"
user-facing-errors = {path = "../../../libs/user-facing-errors", features = ["sql"]}
uuid.workspace = true
indexmap.workspace = true
