[package]
authors = []
edition = "2018"
name = "query-connector"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.31"
chrono = {version = "0.4", features = ["serde"]}
futures = "0.3"
itertools = "0.10"
prisma-models = {path = "../../prisma-models"}
prisma-value = {path = "../../../libs/prisma-value"}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0", features = ["float_roundtrip"]}
thiserror = "1.0"
user-facing-errors = {path = "../../../libs/user-facing-errors"}
uuid = "0.8"
indexmap = "1.0"
