[package]
name = "query-connector"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.2"
prisma-models = { path = "../../../libs/prisma-models" }
failure = { version = "0.1", features = ["derive"] }
uuid = "0.7"
itertools = "0.8"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
user-facing-errors = { path = "../../../libs/user-facing-errors" }

[dev-dependencies]
serde_json = "1"
