[package]
name = "nodejs-drivers"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde.workspace = true
quaint.workspace = true

napi = { version = "2.12.4", default-features = false, features = ["napi8", "tokio_rt", "serde-json"] }
napi-derive = "2.12.3"

[dev-dependencies]
expect-test = "1"
tokio.workspace = true
