[package]
name = "mongodb-schema-describer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb.workspace = true
bson.workspace = true
futures = "0.3"
serde.workspace = true
