[package]
name = "quaint-test-setup"
version = "0.1.0"
authors = ["Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

[dependencies]
bitflags.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
quaint = { workspace = true, features = ["all-native", "pooled"] }
