[package]
name = "core-tests"
version = "0.1.0"
edition.workspace = true

[dependencies]

[dev-dependencies]
dissimilar.workspace = true
user-facing-errors.workspace = true
request-handlers = { workspace = true, features = ["all"] }
query-core.workspace = true
schema.workspace = true
psl.workspace = true
serde_json.workspace = true
