[package]
name = "core-tests"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
dissimilar = "1.0.4"
user-facing-errors = { path = "../../libs/user-facing-errors" }
request-handlers = { path = "../request-handlers" }
query-core = { path = "../core", features = ["metrics"] }
schema = { path = "../schema" }
psl.workspace = true
serde_json.workspace = true
