[package]
name = "prisma"
version = "0.1.0"
authors = ["Dominic Petrick <dompetrick@gmail.com>", "Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[features]
default = ["sql", "graphql"]
sql = ["sql-connector", "quaint"]
graphql = ["graphql-parser"]

[dependencies]
futures-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
http = "0.1"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
tokio = { version = "0.2.0-alpha.6", features = ["tracing"] }

async-trait = "0.1"
lazy_static = "1.4"
prisma-inflector = { path = "../../libs/prisma-inflector" }
datamodel = { path = "../../libs/datamodel/core" }
prisma-models = { path = "../../prisma-models" }
query-core = { path = "../core" }
connector = { path = "../connectors/query-connector", package = "query-connector" }
sql-connector = { path = "../connectors/sql-query-connector", optional = true, package = "sql-query-connector" }
quaint = { git = "https://github.com/prisma/quaint", optional = true }
graphql-parser = { version = "0.2.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = [ "preserve_order" ] }
base64 = "0.10"
rust-embed = { version = "4.3", features = ["debug-embed"] }
failure = "0.1"
failure_derive = "0.1"
indexmap = { version = "1.0", features = [ "serde-1" ] }
itertools = "0.8"
url = "2.1"
clap = "2.33"

tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = { git = "https://github.com/pimeys/tracing", branch = "fix-type-annotations", features = ["json"] }
tracing-attributes = "0.1"
log = "0.4"

[build-dependencies]
rustc_version = "0.2.3"
