name: Build Engines for Apple Intel
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit on the given branch to build"
        required: false

jobs:
  build:
    # Do not change `name`, prisma-engines Buildkite build job depends on this name ending with the commit
    name: "MacOS Intel engines build on branch ${{ github.event.ref }} for commit ${{ github.event.inputs.commit }}"
    env:
      SQLITE_MAX_VARIABLE_NUMBER: 250000
      SQLITE_MAX_EXPR_DEPTH: 10000

      # minimum supported version of macOS
      MACOSX_DEPLOYMENT_TARGET: 10.15
    runs-on: macos-13

    steps:
      - name: Output link to real commit
        run: echo ${{ github.repository }}/commit/${{ github.event.inputs.commit }}

      - name: Checkout ${{ github.event.inputs.commit }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-intel-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: |
          cargo build --release -p query-engine -p query-engine-node-api -p schema-engine-cli -p prisma-fmt

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            ${{ github.workspace }}/target/release/schema-engine
            ${{ github.workspace }}/target/release/prisma-fmt
            ${{ github.workspace }}/target/release/query-engine
            ${{ github.workspace }}/target/release/libquery_engine.dylib
