name: Query Engine
on:
  push:

jobs:

  test:
    name: "Test Query Engine - ${{ matrix.connector }}"
    
    strategy:
      fail-fast: false
      matrix:
        connector: [mysql8]
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: mkdir memsql
      - run: chmod -R 757 memsql
      - run: docker-compose up -d
        env:
          SINGLESTORE_LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE_KEY }}
          
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: query-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Build Engines on image
        run: docker-compose run -e SQLITE_MAX_VARIABLE_NUMBER=250000 -e SQLITE_MAX_EXPR_DEPTH=10000 qe-test-base cargo build --all-features --release --bin query-engine --bin migration-engine          
      
      - name: Run tests on image
        run: docker-compose run -e TEST_CONNECTOR=${{ matrix.connector }} -e TEST_MODE=simple -w /root/build/query-engine/connector-test-kit qe-test-base sbt test

