name: Query Engine
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/query-engine.yml'
      - '.buildkite/**'
      - '*.md'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'renovate.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-query-engine-tests:
    name: 'Test ${{ matrix.database.name }} (${{ matrix.engine_protocol }}) on Linux'

    strategy:
      fail-fast: false
      matrix:
        database:
          - name: 'vitess_8_0'
            single_threaded: true
            connector: 'vitess'
            version: '8.0'
          - name: 'postgres15'
            single_threaded: true
            connector: 'postgres'
            version: '15'
          - name: 'mssql_2022'
            single_threaded: false
            connector: 'sqlserver'
            version: '2022'
          - name: 'mongodb_4_2'
            single_threaded: true
            connector: 'mongodb'
            version: '4.2'
          - name: 'cockroach_23_1'
            single_threaded: false
            connector: 'cockroachdb'
            version: '23.1'
          - name: 'cockroach_22_2'
            single_threaded: false
            connector: 'cockroachdb'
            version: '22.2'
          - name: 'cockroach_22_1_0'
            single_threaded: false
            connector: 'cockroachdb'
            version: '22.1'
        engine_protocol: [graphql, json]

    env:
      LOG_LEVEL: 'info'
      LOG_QUERIES: 'y'
      RUST_LOG_FORMAT: 'devel'
      RUST_BACKTRACE: '1'
      CLICOLOR_FORCE: '1'
      CLOSED_TX_CLEANUP: '2'
      SIMPLE_TEST_MODE: '1'
      QUERY_BATCH_SIZE: '10'
      TEST_RUNNER: 'direct'
      TEST_CONNECTOR: ${{ matrix.database.connector }}
      TEST_CONNECTOR_VERSION: ${{ matrix.database.version }}
      PRISMA_ENGINE_PROTOCOL: ${{ matrix.engine_protocol }}

    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        continue-on-error: true
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        if: "${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Start ${{ matrix.database.name }} (${{ matrix.engine_protocol }})'
        run: make start-${{ matrix.database.name }}

      - uses: dtolnay/rust-toolchain@stable

      - run: export WORKSPACE_ROOT=$(pwd) && cargo test --package query-engine-tests -- --test-threads=1
        if: ${{ matrix.database.single_threaded }}
        env:
          CLICOLOR_FORCE: 1

      - run: export WORKSPACE_ROOT=$(pwd) && cargo test --package query-engine-tests -- --test-threads=8
        if: ${{ !matrix.database.single_threaded }}
        env:
          CLICOLOR_FORCE: 1
