name: Query Engine
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rust-vitess-tests:
    name: "Rust test suite: ${{ matrix.database.name }} on Linux"

    strategy:
      fail-fast: false
      matrix:
        database:
          - name: "vitess_5_7"
          - name: "vitess_8_0"
          - name: "cockroach"
            is_cockroach: true

    env:
      LOG_LEVEL: "info"
      LOG_QUERIES: "y"
      RUST_LOG_FORMAT: "devel"
      RUST_BACKTRACE: 1
      CLICOLOR_FORCE: 1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start ${{ matrix.database.name }}"
        run: make dev-${{ matrix.database.name }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: query-engine-rust-${{ runner.os }}-cargo-vitess-${{ matrix.version }}-${{ hashFiles('**/Cargo.lock') }}

      - run: export WORKSPACE_ROOT=$(pwd) && cargo test --package query-engine-tests -- --test-threads=1
        if: ${{ !matrix.database.is_cockroach }}
        env:
          CLICOLOR_FORCE: 1

      - run: export WORKSPACE_ROOT=$(pwd) && export SIMPLE_TEST_MODE=true && export TEARDOWN_DATABASE=1 && cargo test --package query-engine-tests
        if: ${{ matrix.database.is_cockroach }}
        env:
          CLICOLOR_FORCE: 1
