name: Trigger prisma-engines-builds run
run-name: Trigger prisma-engines-builds run for ${{ github.sha }}


on:
  push:
    branches:
      - main

jobs:
  send-tag-event:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Sending event for commit $GITHUB_SHA"
      - name: Workflow dispatch to prisma/prisma-engines-builds
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: .github/workflows/build-engines.yml
          repo: prisma/prisma-engines-builds
          token: ${{ secrets.BOT_TOKEN_PRISMA_ENGINES_BUILD }}
          inputs: '{ "commit": "${{ github.sha }}" }'
