on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      crate:
        type: string
        required: true

jobs:
  test-crate-compilation:
    name: 'compile ${{ inputs.crate }} @ ${{ inputs.os }}'
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - shell: bash
        if: ${{ runner.os == 'Windows' }}
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static-md

      - name: compile ${{ inputs.crate }}
        shell: bash
        env:
          CRATE: ${{ inputs.crate }}
        run: cargo build --release -p "$CRATE"

      - name: 'Check that Cargo.lock did not change'
        run: 'git diff --exit-code'
