name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
    # skip this CI workflow for integration PRs
    branches-ignore:
      - 'integration/**'
    paths-ignore:
      - '.buildkite/**'
      - '*.md'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'renovate.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Workspace unit tests

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - run: |
            cargo test --workspace \
                  --exclude=query-engine \
                  --exclude=black-box-tests \
                  --exclude=query-engine-tests \
                  --exclude=sql-migration-tests \
                  --exclude=schema-engine-cli \
                  --exclude=sql-schema-describer \
                  --exclude=sql-introspection-tests \
                  --exclude=mongodb-schema-connector
        env:
          CLICOLOR_FORCE: 1
